name: Build & Package .NET

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Initialize and update submodules (redundant but safe)
      run: git submodule update --init --recursive

    - name: Setup .NET 9.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Get project version
      id: get_version
      run: |
        ver=$(dotnet msbuild -nologo -t:GetAssemblyVersion -v:quiet | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
        echo "version=$ver" >> $GITHUB_OUTPUT

    - name: Publish (if applicable)
      run: dotnet publish -c Release -o ./publish

    - name: Pack all necessary files into a ZIP
      run: |
        powershell Compress-Archive -Path ./publish/* -DestinationPath DCS-SRS-RecordingClient-${{ steps.get_version.outputs.version }}.zip

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-zip
        path: DCS-SRS-RecordingClient-*.zip
